name: Update Whitelist

on:
  schedule:
    - cron: "0 */4 * * *"  # every 4 hours
  workflow_dispatch:       # allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ allows push to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run whitelist generator
        working-directory: docs/whitelist
        run: python generate_list.py

      - name: Verify output
        run: |
          echo "Listing generated files..."
          ls -l docs/whitelist

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/whitelist/whitelist.txt
          git status
          git diff --quiet && echo "No changes to commit" || git commit -m "Update whitelist [skip ci]"
          git push
